services:
  traefik:
    image: "traefik:v2.10"
    container_name: "traefik"
    command:
    - "--providers.docker"
    - "--entrypoints.web.address=:80"
    - "--entrypoints.websecure.address=:443"
    #Uncomment to redirect every app to https
    # - "--entrypoints.web.http.redirections.entrypoint.to=websecure"
    # - "--entrypoints.web.http.redirections.entrypoint.scheme=https"
    # Spécifie la redirection en 301 sinon c'est une 302
    # - "--entrypoints.web.http.redirections.entrypoint.permanent=true"
    ports:
    - "80:80"
    - "443:443"
    volumes:
    - "/var/run/docker.sock:/var/run/docker.sock:ro"
    networks:
        - web-applications

  whoami:
    image: "traefik/whoami"
    container_name: "simple-service"
    labels:
    - "traefik.enable=true"
    - "traefik.http.routers.whoami.rule=Host(`whoami.localhost`)"
    - "traefik.http.routers.whoami.entrypoints=websecure"
    - "traefik.http.routers.whoami.tls=true"
    - "traefik.http.routers.whoami-http.entrypoints=web"
    - "traefik.http.routers.whoami-http.rule=Host(`whoami.localhost`)"
    # Uncomment to redirect http to https
    # - "traefik.http.routers.whoami-http.middlewares=whoami-https"
    # - "traefik.http.middlewares.whoami-https.redirectscheme.scheme=https"
    # Spécifie la redirection en 301 sinon c'est une 302
    # - "traefik.http.middlewares.whoami-https.redirectscheme.permanent=true"
    networks:
        - web-applications

networks:
  web-applications:
    name: web-applications
    driver: bridge